### ISSUE TITLE
2.4.5 == 1.4.5? Update Readme

### ISSUE THREAD

**Issue by robertoschwald** [peh/grails-babel-asset-pipeline#10]
Latest version shows 2.4.5 in releases, but the Plugin descriptor states

```
   def version = "1.4.5"
```

and the README states 1.4.2. 

Maybe update the README and release 1.4.5?

**Comment by robertoschwald** [comment]
It seems the release really is 1.4.5 and the README should be updated to reflect it. 2.4.5 seems to be a typo.

https://repo.grails.org/grails/plugins-releases-local/org/grails/plugins/babel-asset-pipeline/1.4.5/babel-asset-pipeline-1.4.5.zip

**Comment by peh** [comment]
hey robert, 
yes this clearly was a typo.
will fix the readme
