### ISSUE TITLE
1.4.5 does not work with Java 7

### ISSUE THREAD

**Issue by robertoschwald** [peh/grails-babel-asset-pipeline#11]
It seems the underlying babel-asset-pipeline 1.4.5 Version was compiled using Java 8, therefore when running e.g. in Grails 2.4.4 using Java 7:

 ERROR asset.pipeline.AssetSpecLoader  - Error loading asset specification asset.pipeline.babel.Es6AssetFile: asset/pipeline/babel/Es6AssetFile : Unsupported major.minor version 52.0
java.lang.UnsupportedClassVersionError: asset/pipeline/babel/Es6AssetFile : Unsupported major.minor version 52.0

**Comment by peh** [comment]
hey, will check that. pretty sure java8 was not needed in the binary plugin

**Comment by peh** [comment]
https://github.com/peh/errbuddy-plugins/commit/357b054eb863859d0b666a2ab9b5b5b87f47191e

released babel-asset-pipeline in a special 1.4.5-java7 version as well as grails-babel-asset-pipeline

can you test it please

**Comment by robertoschwald** [comment]
Works!
