### ISSUE TITLE
How to use this with Grails 3.2.x?

### ISSUE THREAD

**Issue by itpragmatik** [peh/grails-babel-asset-pipeline#13]
Need specific instructions for using this plugin in Grails 3.2.x

Also, can I use this plugin if my goals is this: I already have significant code base written in angular 1.3.x and am working on moving it to angular 2.x gradually and first step is to start refactoring existing code to es6 syntax one by one and so my code base will consist of both: *.js (ES5) and new *.es6 (ES6) files. 

Thanks!

**Comment by peh** [comment]
hey, 

you can find more detailed instructions here https://github.com/errbuddy/babel-asset-pipeline
