### ISSUE TITLE
Using on Java 7

### ISSUE THREAD

**Issue by arianbessonart** [peh/grails-babel-asset-pipeline#15]
Hello. I'm trying use the plugin on Java 7 but the dependency **net.errbuddy.plugins:babel-asset-pipeline** could not resolve. I already saw the issue about this and its seems to works, but no for me.

`                                                                                                                                                                                                 | Downloading: org/grails/plugins/babel-asset-pipeline/1.4.5-java7/babel-asset-pipeline-1.4.5-java7.zip
| Error Resolve error obtaining dependencies: Could not find artifact net.errbuddy.plugins:babel-asset-pipeline:jar:1.4.5-java7 in grailsCentral (http://repo.grails.org/grails/plugins) (Use --stacktrace to see the full trace)
`

Thanks.

**Comment by atript8** [comment]
this is something that you would expect in the documentation rather than fishing for this on the internet.
Add a new repo
mavenRepo "http://dl.bintray.com/errbuddy/plugins"
