### ISSUE TITLE
Grails 3

### ISSUE THREAD

**Issue by Luxor** [peh/grails-babel-asset-pipeline#6]
Hi, 

Do you plan to have grails3 version support.

Thanks

**Comment by peh** [comment]
Hey. You can just use the underlying Binary Plugin:
https://github.com/errbuddy/babel-asset-pipeline in grails3 for now.
I will Look into upgrading this Plugin.

**Comment by Luxor** [comment]
Cool. Thanks

**Comment by peh** [comment]
since a few days babel-asset-pipeline is in grails-3 repo on bintray

**Comment by Luxor** [comment]
Thanks
